In [8]:
import numpy as np
from numpy.random import randint as ri

# Write a function so that the columns of the output matrix are powers of the input vector.

In [21]:
a = np.array([[1,2,3]])


In [22]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)

In [23]:
mat2 = mat1**a.T

In [24]:
mat1

array([[9, 1, 9],
       [1, 9, 4],
       [5, 3, 2]])

In [30]:
print('Result ---------------------------------\n',mat2)

Result ---------------------------------
 [[  9   1   9]
 [  1  81  16]
 [125  27   8]]


# The moving averages

In [18]:
def movingAvg(arg,wSize):
    lenArg = len(arg)
    mAvg = []
    
    for i in range(lenArg):
        counter = 0
        if i==lenArg-wSize+1:
            break
        for j in range(i,i+wSize):
            counter += arg[j]
        counter = counter / wSize
        mAvg.append(counter)
    print(mAvg)

In [19]:
b = [10,20,30,40,50,60,70,80,90,100]

In [20]:
movingAvg(b,4)

[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]
